import math


RES = WIDTH, HEIGHT = 1600, 1000
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 4
FPS = 60

PLAYER_POS = 1.5, 1.5 #mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_HEIGHT_SCALE = 1
CAMERA_HEIGHT = 0.4
PLAYER_EYE_LEVEL = 0.1


FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
